editor-command.ast.gen.o: editor-command.ast.gen.fwd.h
editor-global.o: editor-command.ast.gen.fwd.h
editor-widget-frame.o: editor-command.ast.gen.fwd.h
editor-widget.moc.o: editor-command.ast.gen.fwd.h
editor-widget.o: editor-command.ast.gen.fwd.h
editor-widget.o: editor-command.ast.gen.h
editor-widget.o: smqtutil/courB24_ISO8859_1.bdf.gen.h
editor-widget.o: smqtutil/courO24_ISO8859_1.bdf.gen.h
editor-widget.o: smqtutil/courR24_ISO8859_1.bdf.gen.h
editor-widget.o: smqtutil/editor14b.bdf.gen.h
editor-widget.o: smqtutil/editor14i.bdf.gen.h
editor-widget.o: smqtutil/editor14r.bdf.gen.h
editor-widget.o: smqtutil/minihex6.bdf.gen.h
editor-window.o: editor-command.ast.gen.fwd.h
editor-window.o: keybindings.doc.gen.h
sar-panel.o: editor-command.ast.gen.fwd.h
